### ISSUE TITLE
自動ビルドしたexeファイルを実行してAPIを叩くとエラー

### ISSUE THREAD

**Issue by Hiroshiba** [Hiroshiba/voicevox_engine#130]
## 不具合の内容

0.7.0用にビルドしたartifactにあるrun.exeを実行してAPIを叩くとエラーが出ました。
https://github.com/Hiroshiba/voicevox_engine/actions/runs/1323355607

### 現象・ログ

<details>

```bash
[32mINFO[0m:     Started server process [[36m25920[0m]
[32mINFO[0m:     Waiting for application startup.
[32mINFO[0m:     Application startup complete.
[32mINFO[0m:     Uvicorn running on [1mhttp://127.0.0.1:50021[0m (Press CTRL+C to quit)
[32mINFO[0m:     127.0.0.1:52381 - "[1mGET /version HTTP/1.1[0m" [91m500 Internal Server Error[0m
[31mERROR[0m:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\hihok\DOWNLO~1\WINDOW~1\anyio\_core\_eventloop.py", line 140, in get_asynclib
KeyError: 'anyio._backends._asyncio'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\hihok\DOWNLO~1\WINDOW~1\uvicorn\protocols\http\h11_impl.py", line 373, in run_asgi
  File "C:\Users\hihok\DOWNLO~1\WINDOW~1\uvicorn\middleware\proxy_headers.py", line 75, in __call__
  File "C:\Users\hihok\DOWNLO~1\WINDOW~1\fastapi\applications.py", line 208, in __call__
  File "C:\Users\hihok\DOWNLO~1\WINDOW~1\starlette\applications.py", line 112, in __call__
  File "C:\Users\hihok\DOWNLO~1\WINDOW~1\starlette\middleware\errors.py", line 159, in __call__
  File "C:\Users\hihok\DOWNLO~1\WINDOW~1\starlette\middleware\cors.py", line 84, in __call__
  File "C:\Users\hihok\DOWNLO~1\WINDOW~1\starlette\exceptions.py", line 71, in __call__
  File "C:\Users\hihok\DOWNLO~1\WINDOW~1\starlette\routing.py", line 656, in __call__
  File "C:\Users\hihok\DOWNLO~1\WINDOW~1\starlette\routing.py", line 259, in handle
  File "C:\Users\hihok\DOWNLO~1\WINDOW~1\starlette\routing.py", line 61, in app
  File "C:\Users\hihok\DOWNLO~1\WINDOW~1\fastapi\routing.py", line 226, in app
  File "C:\Users\hihok\DOWNLO~1\WINDOW~1\fastapi\routing.py", line 161, in run_endpoint_function
  File "C:\Users\hihok\DOWNLO~1\WINDOW~1\starlette\concurrency.py", line 39, in run_in_threadpool
  File "C:\Users\hihok\DOWNLO~1\WINDOW~1\anyio\to_thread.py", line 28, in run_sync
  File "C:\Users\hihok\DOWNLO~1\WINDOW~1\anyio\_core\_eventloop.py", line 142, in get_asynclib
  File "importlib.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'anyio._backends'

```

</details>

## VOICEVOXのバージョン

0.?.0

## その他

python、ビルド後に実行すると何かが変わっていて思ったより実行できないことがある気がします。
ビルド後にrun.exeを実行して、適当なAPIが実行できるか試してもいいかも。

requirements.txtはもうちょっとバージョン固定してもいいかも。
あとは、pipenvかpoetryを使ってlockを作ってもいいかも。

**Comment by Hiroshiba** [comment]
release-0.7ブランチ内で解決策を試してみています
https://github.com/Hiroshiba/voicevox_engine/commit/0e8f748f3e0044b560468af2807c52f62d2f7472
