### ISSUE TITLE
製品版 VOICEVOX でのサーバー起動について

### ISSUE THREAD

**Issue by k-kuroguro** [Hiroshiba/voicevox_engine#21]
READMEには以下の様に記載してありますが、`PYTHONPATH`には`VOICEVOX_DIR`を入れるべきではないでしょうか。
自分の環境では、以下のコードでは動かず、`VOICEVOX_DIR`に変更すると動作しました。(pythonは`PYTHONPATH`内のモジュールを読み込むようなので、`each_cpp_forwarder`がimportされていませんでした。)

```
# 製品版 VOICEVOX でサーバーを起動
VOICEVOX_DIR="C:/path/to/voicevox" # 製品版 VOICEVOX ディレクトリのパス
CODE_DIRECTORY=$(pwd) # コードがあるディレクトリのパス
cd $VOICEVOX_DIR
PYTHONPATH=$CODE_DIRECTORY python $CODE_DIRECTORY/run.py
```

**Comment by Hiroshiba** [comment]
`PYTHONPATH=$VOICEVOX_DIR`だと起動はしますが、たぶん音声合成に失敗すると思います。

たぶんどの環境でも上記のコードで音声合成できるサーバーが起動すると思います。
途中にある`cd $VOICEVOX_DIR`は実行されましたか？

**Comment by k-kuroguro** [comment]
READMEの通りにcurlコマンドを実行し、正常に`wav`ファイルに書き出されていることは確認しました。

実際に実行すると以下の結果になります。
```bash
$ VOICEVOX_DIR="D:/VOICEVOX"         
                                                                                                                              
$ CODE_DIRECTORY=$(pwd)

$ cd $VOICEVOX_DIR

$ PYTHONPATH=$CODE_DIRECTORY python $CODE_DIRECTORY/run.py
INFO:     Started server process [28168]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:50021 (Press CTRL+C to quit)
INFO:     127.0.0.1:53417 - "POST /audio_query?text=ABCDEFG&speaker=1 HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "D:\Python37\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "D:\Python37\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "D:\Python37\lib\site-packages\fastapi\applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "D:\Python37\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\Python37\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    raise exc from None
  File "D:\Python37\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "D:\Python37\lib\site-packages\starlette\middleware\cors.py", line 78, in __call__
    await self.app(scope, receive, send)
  File "D:\Python37\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    raise exc from None
  File "D:\Python37\lib\site-packages\starlette\exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "D:\Python37\lib\site-packages\starlette\routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "D:\Python37\lib\site-packages\starlette\routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "D:\Python37\lib\site-packages\starlette\routing.py", line 52, in app
    response = await func(request)
  File "D:\Python37\lib\site-packages\fastapi\routing.py", line 220, in app
    dependant=dependant, values=values, is_coroutine=is_coroutine
  File "D:\Python37\lib\site-packages\fastapi\routing.py", line 154, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "D:\Python37\lib\site-packages\starlette\concurrency.py", line 40, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "D:\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:/Users/81701/Desktop/voicevox_engine/run.py", line 121, in audio_query
    accent_phrases=create_accent_phrases(text, speaker_id=speaker),
  File "C:/Users/81701/Desktop/voicevox_engine/run.py", line 107, in create_accent_phrases
    speaker_id=speaker_id,
  File "C:/Users/81701/Desktop/voicevox_engine/run.py", line 66, in replace_mora_pitch
    accent_phrases=accent_phrases, speaker_id=speaker_id
  File "C:\Users\81701\Desktop\voicevox_engine\voicevox_engine\synthesis_engine.py", line 220, in extract_phoneme_f0
    speaker_id=numpy.array(speaker_id, dtype=numpy.int64).reshape(-1),
TypeError: yukarin_sa_forward() got an unexpected keyword argument 'length'
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [28168]

$ PYTHONPATH=$VOICEVOX_DIR python $CODE_DIRECTORY/run.py
INFO:     Started server process [22420]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:50021 (Press CTRL+C to quit)
INFO:     127.0.0.1:52245 - "POST /audio_query?text=ABCDEFG&speaker=1 HTTP/1.1" 200 OK
[W ..\..\aten\src\ATen\native\BinaryOps.cpp:467] Warning: floor_divide is deprecated, and will be removed in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values.
To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor'). (function operator ())
INFO:     127.0.0.1:58760 - "POST /synthesis?speaker=1 HTTP/1.1" 200 OK
```

一度目の`run.py`実行では、以下のコマンドで上記のエラーが出ます。
```
curl -s \
    -X POST \
    "localhost:50021/audio_query?text=$text&speaker=1"\
    > query.json
```

**Comment by Hiroshiba** [comment]
すみません、仰るとおり逆でした・・・。自分用に作っていた環境が偶然正しそうに動作していただけでした。
ご指摘ありがとうございます。READMEを修正したいと思います。
