### ISSUE TITLE
特定の文字列の音声合成用のクエリ作成に失敗する

### ISSUE THREAD

**Issue by raa0121** [Hiroshiba/voicevox_engine#55]
## 不具合の内容

特定の文字列の音声合成用のクエリ作成に失敗する

### 現象・ログ

<details><summary>172.16.0.1</summary><div>

```
INFO:     127.0.0.1:54944 - "POST /audio_query?text=172.16.0.1&speaker=1 HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\home\develop\voicevox_engine\.venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "C:\home\develop\voicevox_engine\.venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "C:\home\develop\voicevox_engine\.venv\lib\site-packages\fastapi\applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "C:\home\develop\voicevox_engine\.venv\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\home\develop\voicevox_engine\.venv\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    raise exc from None
  File "C:\home\develop\voicevox_engine\.venv\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "C:\home\develop\voicevox_engine\.venv\lib\site-packages\starlette\middleware\cors.py", line 86, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "C:\home\develop\voicevox_engine\.venv\lib\site-packages\starlette\middleware\cors.py", line 142, in simple_response
    await self.app(scope, receive, send)
  File "C:\home\develop\voicevox_engine\.venv\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    raise exc from None
  File "C:\home\develop\voicevox_engine\.venv\lib\site-packages\starlette\exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "C:\home\develop\voicevox_engine\.venv\lib\site-packages\starlette\routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "C:\home\develop\voicevox_engine\.venv\lib\site-packages\starlette\routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "C:\home\develop\voicevox_engine\.venv\lib\site-packages\starlette\routing.py", line 52, in app
    response = await func(request)
  File "C:\home\develop\voicevox_engine\.venv\lib\site-packages\fastapi\routing.py", line 220, in app
    dependant=dependant, values=values, is_coroutine=is_coroutine
  File "C:\home\develop\voicevox_engine\.venv\lib\site-packages\fastapi\routing.py", line 154, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "C:\home\develop\voicevox_engine\.venv\lib\site-packages\starlette\concurrency.py", line 40, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "C:\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "run.py", line 177, in audio_query
    accent_phrases=create_accent_phrases(text, speaker_id=speaker),
  File "run.py", line 163, in create_accent_phrases
    speaker_id=speaker_id,
  File "run.py", line 113, in replace_mora_data
    accent_phrases=accent_phrases, speaker_id=speaker_id
  File "C:\home\develop\voicevox_engine\voicevox_engine\synthesis_engine.py", line 149, in replace_phoneme_data
    for accent_phrase in accent_phrases
  File "C:\home\develop\voicevox_engine\voicevox_engine\synthesis_engine.py", line 149, in <listcomp>
    for accent_phrase in accent_phrases
IndexError: index 2 is out of bounds for axis 0 with size 2
```
</div></details>

<details><summary>か。ら</summary><div>

```
INFO:     127.0.0.1:54778 - "POST /audio_query?text=%E3%81%8B%E3%80%82%E3%82%89&speaker=1 HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\home\develop\voicevox_engine\.venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "C:\home\develop\voicevox_engine\.venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "C:\home\develop\voicevox_engine\.venv\lib\site-packages\fastapi\applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "C:\home\develop\voicevox_engine\.venv\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\home\develop\voicevox_engine\.venv\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    raise exc from None
  File "C:\home\develop\voicevox_engine\.venv\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "C:\home\develop\voicevox_engine\.venv\lib\site-packages\starlette\middleware\cors.py", line 86, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "C:\home\develop\voicevox_engine\.venv\lib\site-packages\starlette\middleware\cors.py", line 142, in simple_response
    await self.app(scope, receive, send)
  File "C:\home\develop\voicevox_engine\.venv\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    raise exc from None
  File "C:\home\develop\voicevox_engine\.venv\lib\site-packages\starlette\exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "C:\home\develop\voicevox_engine\.venv\lib\site-packages\starlette\routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "C:\home\develop\voicevox_engine\.venv\lib\site-packages\starlette\routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "C:\home\develop\voicevox_engine\.venv\lib\site-packages\starlette\routing.py", line 52, in app
    response = await func(request)
  File "C:\home\develop\voicevox_engine\.venv\lib\site-packages\fastapi\routing.py", line 220, in app
    dependant=dependant, values=values, is_coroutine=is_coroutine
  File "C:\home\develop\voicevox_engine\.venv\lib\site-packages\fastapi\routing.py", line 154, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "C:\home\develop\voicevox_engine\.venv\lib\site-packages\starlette\concurrency.py", line 40, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "C:\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "run.py", line 177, in audio_query
    accent_phrases=create_accent_phrases(text, speaker_id=speaker),
  File "run.py", line 163, in create_accent_phrases
    speaker_id=speaker_id,
  File "run.py", line 113, in replace_mora_data
    accent_phrases=accent_phrases, speaker_id=speaker_id
  File "C:\home\develop\voicevox_engine\voicevox_engine\synthesis_engine.py", line 137, in replace_phoneme_data
    for accent_phrase in accent_phrases
  File "C:\home\develop\voicevox_engine\voicevox_engine\synthesis_engine.py", line 137, in <listcomp>
    for accent_phrase in accent_phrases
IndexError: index 1 is out of bounds for axis 0 with size 1
```
</div></details>

### 再現手順

```
$ curl -X 'POST'   'http://localhost:50021/audio_query?text=172.16.0.1&speaker=1'
Internal Server Error
```

### 期待動作

json が生成される

## VOICEVOXのバージョン

0.4.0

## OSの種類/ディストリ/バージョン

*   Windows 10 Home 64bit 21H1 (19043.1165)

**Comment by Hiroshiba** [comment]
理由はわかりませんが、エラーが出ている場所はおそらくここです。
https://github.com/Hiroshiba/voicevox_engine/blob/39b5abf5ba36283f3f3bc9241fab3383a17c9220/voicevox_engine/synthesis_engine.py#L144

たぶん`accent_phrase.accent - 1 > len(accent_phrase.moras) + 1`になっている、つまりアクセント位置`accent_phrase.accent`が文字数`len(accent_phrase.moras)`を超えています。
なんでだろう、もしかしたら変なバグがあるかもしれません・・・。

**Comment by raa0121** [comment]
172.16.0.1の `accent_phrase` の値 をダンプしてみました。
```python
  AccentPhrase(
    moras=[
      Mora(text='イ', consonant=None, consonant_length=None, vowel='i', vowel_length=0.0, pitch=0.0),
      Mora(text='チ', consonant='ch', consonant_length=0.0, vowel='i', vowel_length=0.0, pitch=0.0)
    ],
    accent=3,
    pause_mora=None
  ),
```
ここが悪い可能性が高いです。

<details><summary>172.16.0.1のaccent_phraseの値</summary><div>

```python
[
  AccentPhrase(
    moras=[
      Mora(text='ヒャ', consonant='hy', consonant_length=0.0, vowel='a', vowel_length=0.0, pitch=0.0),
      Mora(text='ク', consonant='k', consonant_length=0.0, vowel='u', vowel_length=0.0, pitch=0.0)
    ],
    accent=2,
    pause_mora=None
  ),
  AccentPhrase(
    moras=[
      Mora(text='ナ', consonant='n', consonant_length=0.0, vowel='a', vowel_length=0.0, pitch=0.0),
      Mora(text='ナ', consonant='n', consonant_length=0.0, vowel='a', vowel_length=0.0, pitch=0.0),
      Mora(text='ジュ', consonant='j', consonant_length=0.0, vowel='u', vowel_length=0.0, pitch=0.0),
      Mora(text='ウ', consonant=None, consonant_length=None, vowel='u', vowel_length=0.0, pitch=0.0)
    ],
    accent=1,
    pause_mora=None
  ),
  AccentPhrase(
    moras=[
      Mora(text='ニ', consonant='n', consonant_length=0.0, vowel='i', vowel_length=0.0, pitch=0.0),
      Mora(text='イ', consonant=None, consonant_length=None, vowel='i', vowel_length=0.0, pitch=0.0),
      Mora(text='テ', consonant='t', consonant_length=0.0, vowel='e', vowel_length=0.0, pitch=0.0),
      Mora(text='ン', consonant=None, consonant_length=None, vowel='N', vowel_length=0.0, pitch=0.0)
    ],
    accent=1,
    pause_mora=None
  ),
  AccentPhrase(
    moras=[
      Mora(text='イ', consonant=None, consonant_length=None, vowel='i', vowel_length=0.0, pitch=0.0),
      Mora(text='チ', consonant='ch', consonant_length=0.0, vowel='i', vowel_length=0.0, pitch=0.0)
    ],
    accent=3,
    pause_mora=None
  ),
  AccentPhrase(
    moras=[
      Mora(text='ロ', consonant='r', consonant_length=0.0, vowel='o', vowel_length=0.0, pitch=0.0),
      Mora(text='ク', consonant='k', consonant_length=0.0, vowel='u', vowel_length=0.0, pitch=0.0),
      Mora(text='テ', consonant='t', consonant_length=0.0, vowel='e', vowel_length=0.0, pitch=0.0),
      Mora(text='ン', consonant=None, consonant_length=None, vowel='N', vowel_length=0.0, pitch=0.0)
    ],
    accent=2,
    pause_mora=None
  ),
  AccentPhrase(
    moras=[
        Mora(text='レ', consonant='r', consonant_length=0.0, vowel='e', vowel_length=0.0, pitch=0.0),
        Mora(text='エ', consonant=None, consonant_length=None, vowel='e', vowel_length=0.0, pitch=0.0),
        Mora(text='テ', consonant='t', consonant_length=0.0, vowel='e', vowel_length=0.0, pitch=0.0),
        Mora(text='ン', consonant=None, consonant_length=None, vowel='N', vowel_length=0.0, pitch=0.0)
    ],
    accent=1,
    pause_mora=None
  ),
  AccentPhrase(
    moras=[
      Mora(text='イ', consonant=None, consonant_length=None, vowel='i', vowel_length=0.0, pitch=0.0),
      Mora(text='チ', consonant='ch', consonant_length=0.0, vowel='i', vowel_length=0.0, pitch=0.0)
    ],
    accent=2,
    pause_mora=None
  )
]```
</div></details>

**Comment by Hiroshiba** [comment]
なるほどです。accent=3になってるのが原因で間違いないと思います。
accentの計算はこの辺なのですが、調査をお願いしてもいいですか・・・？ @raa0121 
https://github.com/Hiroshiba/voicevox_engine/blob/5e04069356e825f9d0584ffd2872b251782e7ead/voicevox_engine/full_context_label.py#L109

やり方わからなかったら何でも聞いて頂ければ！

**Comment by y-chan** [comment]
それぞれの文字列をpyopenjtalkに投げた結果の時点で既に何かおかしいのでは、と思い(voicevox engine側で値の利用方法を誤っているか、openjtalk側に問題があるのかは不明)簡易的なスクリプトを組んで調べてみました。
`f2`はアクセントとして実際に用いられている値、`p3`は音素です。
また、灰色でマークしているところが実際に問題となっていそうなアクセントの値です。
まだopenjtalkが吐くcontextのすべてを理解しているわけではないので、わからないですが`f2`はもしかしたらアクセントではない...?
![image](https://user-images.githubusercontent.com/34832037/131617272-f2777a65-c7c8-417c-b9dc-e0bdc1f27aa6.png)
![image](https://user-images.githubusercontent.com/34832037/131617629-6b09c6e9-0897-4065-8bea-8ffafc09500e.png)

**Comment by raa0121** [comment]
@Hiroshiba 引き続き調べてみますね。
@y-chan おぉ、調査ありがとうございます。こちらでも見てみます。

**Comment by y-chan** [comment]
> もしよかったら最小のサンプルコードも提示いただけると、みんなの知識量が上がって良いかもです

元のコメントに追記しました！

**Comment by raa0121** [comment]
まずは、フルコンテキストラベルを Phoneme にパースする正規表現 https://github.com/Hiroshiba/voicevox_engine/blob/5e04069356e825f9d0584ffd2872b251782e7ead/voicevox_engine/full_context_label.py#L16-L27 を確認してみましたが、厳密な正規表現 ( `[^-]+` 等を使う) と、現状のもので、同じマッチになりました。
ラベルの解析が間違ってる可能性が高いです。
公式で配布されてるフォーマットの英文は少しずつ、翻訳しながら読んでみてます。

**Comment by y-chan** [comment]
軽く調べてみたところ、以下のようなサイトを見つけました。
https://www.negi.moe/negitalk/openjtalk.html

このサイトの下のほうでは、辞書によってはアクセント核とモーラ数が一致しないものが存在するとあります。
憶測ではありますが、これが影響してる可能性があるかもしれません。

**Comment by Hiroshiba** [comment]
@raa0121 調査ありがとうございます。VOICEVOX側のコードは問題なさそうな感じですかね。。
@y-chan な、なるほど・・・VOICEVOX側ではもうどうしようもないかもですね・・・

openjtalkの辞書を書き換えるのはかなり手間な気がしますね。。
悲しいですが、もうアクセント位置がモーラ数を超えていた場合は無理やりクリップするのが妥当な気がしてきました。

**Comment by Hiroshiba** [comment]
ワークアラウンドが実装されたのでいったん閉じます。

**Comment by qryxip** [comment]
ちょっと興味が湧いたのでCodexに調べさせたんですが、Open JTalkは`か。ら`を「`[か, pau, ら]`というひとまとまりのbreath groupであり、ひとまとまりのアクセント句であり、モーラ数は`2`（`か`と`ら`）でアクセント位置は`2`（`ら`）」と解釈するようです。そしてVOICEVOXはそれを以下のように分割する。

- モーラ列=`[か, pau]`, アクセント=`2`（本来はアクセント句`[か, pau, ら]`に対するアクセント位置）
- モーラ列=`[ら]`, アクセント=`2`（〃）

なので少なくとも`か。ら`は

> このサイトの下のほうでは、辞書によってはアクセント核とモーラ数が一致しないものが存在するとあります。

にはあてはまらなさそうです。

一方で`172.16.0.1`については、当時のVOICEVOXでは実際に`/F:2_3`（モーラ数`2`にアクセント位置`3`）が出てしまっていた…らしい。ただし辞書によるものではなく、処理側の「digit rules」の不備によるもののようです。本家Open JTalkのv1.10 → v1.11で、以下のリリースノートをもって解決したんだとか。

> * add digit rules for digits including comma.

なので`172.16.0.1`に対しては #58 のワークアラウンドはもう発動しないようです（`か。ら`に対しては発動する）。
