### ISSUE TITLE
日本語ディレクトリだとエンジンが起動しない

### ISSUE THREAD

**Issue by Hiroshiba** [Hiroshiba/voicevox_engine#76]
## 不具合の内容

日本語ディレクトリだとエンジンが起動しない

### 現象・ログ

コアライブラリに日本語入りの絶対パスが渡ってきて落ちる。

```bash
$ ./run.exe
Traceback (most recent call last):
  File "C:\Users\hihok\DOWNLO~1\\u30dc\u30a4\u30dc\run.py", line 257, in <module>
  File "C:\Users\hihok\DOWNLO~1\\u30dc\u30a4\u30dc\run.py", line 61, in make_synthesis_engine
  File "core.pyx", line 6, in core.initialize
  File "core.pyx", line 14, in core.initialize
AssertionError
```

## その他

コアライブラリが日本語に耐えられるようにするのが一番良さそう。
もしくは絶対パス`__FILE__`を相対パスにして直るならとりあえずそれでも良さそう。

**Comment by Hiroshiba** [comment]
遭遇された方のツイート　https://twitter.com/Vtuber_Mochio/status/1436033008457306114

**Comment by Hiroshiba** [comment]
0.5.2で解決されたはずなのでclose
