### ISSUE TITLE
Mock 版で起動しない

### ISSUE THREAD

**Issue by buckw6eat** [Hiroshiba/voicevox_engine#79]
## 不具合の内容

#78 マージ後より Mock 版 (voicevox-dir を指定しない、このプロジェクト単独での実行) で起動しない

### 現象・ログ

```bash
$ python run.py
Notice: mock-library will be used. Try re-run with valid --voicevox_dir
Traceback (most recent call last):
  File "run.py", line 331, in <module>
    voicelib_dir=args.voicelib_dir,
  File "run.py", line 81, in make_synthesis_engine
    from voicevox_engine.dev.synthesis_engine import (
  File "C:\github\voicevox_engine\voicevox_engine\dev\synthesis_engine\__init__.py", line 1, in <module>
    from .mock import SynthesisEngine
  File "C:\github\voicevox_engine\voicevox_engine\dev\synthesis_engine\mock.py", line 13, in <module>
    class SynthesisEngine:
  File "C:\github\voicevox_engine\voicevox_engine\dev\synthesis_engine\mock.py", line 64, in SynthesisEngine
    def synthesis(self, query: AudioQuery, speaker_id: int) -> npt.NDArray[np.int16]:
AttributeError: module 'numpy.typing' has no attribute 'NDArray'
```

<details>
<summary>pip list (パッケージ一覧)</summary>

```bash
$ pip list
Package            Version
------------------ -------------
aiofiles           0.7.0
asgiref            3.4.1
cffi               1.14.6
click              8.0.1
colorama           0.4.4
Cython             0.29.24
fastapi            0.68.1
h11                0.12.0
importlib-metadata 4.8.1
llvmlite           0.37.0
numba              0.54.0
numpy              1.20.0
pip                20.1.1
pycparser          2.20
pydantic           1.8.2
pyopenjtalk        0.1.4+69e5f35
python-multipart   0.0.5
resampy            0.2.2
scipy              1.7.1
setuptools         47.1.0
six                1.16.0
SoundFile          0.10.3.post1
starlette          0.14.2
typing-extensions  3.10.0.2
uvicorn            0.15.0
zipp               3.5.0
WARNING: You are using pip version 20.1.1; however, version 21.2.4 is available.
You should consider upgrading via the 'c:\github\voicevox_engine\venv-check-marged-87\scripts\python.exe -m pip install --upgrade pip' command.
```

</details>

### 再現手順

```bash
# venv 新しく作る
python -m venv venv-check-issue-79
source venv-check-issue-79/Scripts/Activate

# 依存関係インストール
pip install -r requirements.txt

# Mock でエンジン実行
python run.py
```

### 期待動作

エンジンが起動すること。

## VOICEVOXのバージョン

0.5.1 5ed623e

## OSの種類/ディストリ/バージョン

*   Windows 10 Pro 64bit (10.0.19043)

## その他

`numpy.typing,NDArray` はかなり最近の機能である。
https://github.com/numpy/numpy/releases/tag/v1.21.0

> ### A runtime-subcriptable alias has been added for ndarray
> 
> numpy.typing.NDArray has been added, a runtime-subscriptable alias for
> np.ndarray[Any, np.dtype[~Scalar]]. The new type alias can be used for
> annotating arrays with a given dtype and unspecified shape.

**Comment by buckw6eat** [comment]
補足： `pipdeptree` というツールで package が依存/指定する package が分かるようです。

```bash
$ pip install pipdeptree

(snip)

$ pipdeptree
aiofiles==0.7.0
fastapi==0.68.1
  - pydantic [required: >=1.6.2,<2.0.0,!=1.8.1,!=1.8,!=1.7.3,!=1.7.2,!=1.7.1,!=1.7, installed: 1.8.2]
    - typing-extensions [required: >=3.7.4.3, installed: 3.10.0.2]
  - starlette [required: ==0.14.2, installed: 0.14.2]
pipdeptree==2.1.0
  - pip [required: >=6.0.0, installed: 20.1.1]
pyopenjtalk==0.1.4+69e5f35
  - cython [required: >=0.21.0, installed: 0.29.24]
  - numpy [required: >=1.8.0, installed: 1.20.0]
  - six [required: Any, installed: 1.16.0]
python-multipart==0.0.5
  - six [required: >=1.4.0, installed: 1.16.0]
resampy==0.2.2
  - numba [required: >=0.32, installed: 0.54.0]
    - llvmlite [required: >=0.37.0rc1,<0.38, installed: 0.37.0]
    - numpy [required: >=1.17,<1.21, installed: 1.20.0]
    - setuptools [required: Any, installed: 47.1.0]
  - numpy [required: >=1.10, installed: 1.20.0]
  - scipy [required: >=0.13, installed: 1.7.1]
    - numpy [required: >=1.16.5,<1.23.0, installed: 1.20.0]
  - six [required: >=1.3, installed: 1.16.0]
SoundFile==0.10.3.post1
  - cffi [required: >=1.0, installed: 1.14.6]
    - pycparser [required: Any, installed: 2.20]
uvicorn==0.15.0
  - asgiref [required: >=3.4.0, installed: 3.4.1]
    - typing-extensions [required: Any, installed: 3.10.0.2]
  - click [required: >=7.0, installed: 8.0.1]
    - colorama [required: Any, installed: 0.4.4]
    - importlib-metadata [required: Any, installed: 4.8.1]
      - typing-extensions [required: >=3.6.4, installed: 3.10.0.2]
      - zipp [required: >=0.5, installed: 3.5.0]
  - h11 [required: >=0.8, installed: 0.12.0]
  - typing-extensions [required: Any, installed: 3.10.0.2]
 ```

といいますか、要するにこの子がよくないんですよね。

> resampy==0.2.2
>  - numba [required: >=0.32, installed: 0.54.0]
>    - llvmlite [required: >=0.37.0rc1,<0.38, installed: 0.37.0]
>    - **numpy [required: >=1.17,<1.21, installed: 1.20.0]**
>    - setuptools [required: Any, installed: 47.1.0]

**Comment by Hiroshiba** [comment]
なるほどです！

resampyを使わないようにするか、`numpy<1.21`でも動くようにするかでしょうか。
resampyは優秀なリサンプリングライブラリなので代替を探すのは知識が必要かもしれません。
ので、とりあえず後者が良いと思います。`npt.NDArray[np.int16`のところを消すか、`np.ndarray`に変えれば大丈夫かもです。
